### PR TITLE
Elasticsearch integration

### PR DESCRIPTION
**Pull request by pykcel**
Enable to query an Elasticsearch server with the python API. We need to specify the url, index name, the fields to search on and the field name containing the text to retrieve. It works as follow on an existing drqa model:
```
DrQA.process(self, query, candidates=None, top_n=1, n_docs=5, 
             return_context=False, elastic_url='localhost:9200', elastic_index='pmpsa', 
             elastic_fields=['content.unigrams', 'content.bigrams', 'doc_name^2'], elastic_text_field='content')
```

### CODE REVIEW

**Comment by GhostAtom** [comment]
Hi @pykcel, do you have the Elasticsearch mapping required for the query ? Thanks

**Comment by ajfisch** [comment]
Thanks for the contribution! 

(a) If you could you please sign the CLA, that would be great.

(b) My suggestion is to move the elastic search params into the initialization. That way we can skip loading the DB (which isn't used).

**Comment by pykcel** [comment]
Hi @ajfisch, it makes sense, I will do the necessary.

Hi @GhostAtom, I can share the elastic mapping but the idea should be generic and replicable to any index designed for full text search.

**Comment by pykcel** [comment]
Moved the ES params in the initialization of the ranker, E.g.:
```
from drqa.pipeline import DrQA
from drqa.retriever import ElasticDocRanker
model = DrQA(cuda=False, reader_model='data/reader/multitask.mdl', ranker_config={'class':ElasticDocRanker, 'options':{'elastic_url':'127.0.0.1:9200', 'elastic_fields':'content', 'elastic_index':'mini', 'elastic_field_doc_name':['file', 'filename'], 'elastic_field_content': 'content'}})
model.process('How many knives are there on the drums?', return_context=True)
```
Please feel free to review/comment in order to make the adaptation if necessary. If interested, I'll update the documentation

**Comment by ajfisch** [comment]
Thanks for the contribution! I'll review in a few days.

**Pull request merged**
